import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { TOOL_NAME, TOOL_VERSION } from './constants.js'
import { sanitizeFileName, writeJson } from './utils.js'

function escapeMd(value) { return String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ') }
function symbol(level) { return ({ pass: '✅', warning: '⚠️', error: '❌', info: 'ℹ️' })[level] ?? '•' }

export function markdownReport(report) {
  const lines = [
    `# DSH Plugin Doctor: ${report.plugin.name ?? report.source}`,
    '',
    `- Result: **${report.status.toUpperCase()}**`,
    `- Plugin: \`${report.plugin.name ?? 'unknown'}@${report.plugin.version ?? 'unknown'}\``,
    `- Generated: ${report.generatedAt}`,
    `- Doctor: ${report.tool.version}`,
    '',
    '## Compatibility checks', '',
    '| Result | Check | Detail |', '|---|---|---|',
    ...report.checks.map(item => `| ${symbol(item.level)} ${item.level} | \`${escapeMd(item.id)}\` | ${escapeMd(item.message)} |`),
    '', '## Security findings', '',
  ]
  if (report.findings.length === 0) lines.push('No high-risk behavior signatures were found.')
  else {
    lines.push('| Severity | Permission | Location | Evidence |', '|---|---|---|---|')
    for (const item of report.findings) {
      lines.push(`| ${item.severity} | \`${item.permission}\` | ${escapeMd(item.file)}${item.line ? `:${item.line}` : ''} | ${escapeMd(item.evidence)} |`)
    }
  }
  lines.push('', '## Permission manifest', '')
  if (report.permissions.permissions.length === 0) lines.push('No permissions inferred.')
  else for (const item of report.permissions.permissions) lines.push(`- **${item.permission}** (${item.severity}): ${item.reasons.join('; ')} — ${item.files.join(', ')}`)

  lines.push('', '## Cordis configuration entries', '')
  if (report.permissions.cordisEntries.length === 0) lines.push('No plugin rows inferred from the bundle patch.')
  else lines.push('```json', JSON.stringify(report.permissions.cordisEntries, null, 2), '```')

  if (report.regressions?.length) {
    lines.push('', '## DSH regression matrix', '', '| DSH | Result | Startup |', '|---|---|---|')
    for (const item of report.regressions) lines.push(`| ${escapeMd(item.version)} | ${item.status} | ${escapeMd(item.startup?.message ?? 'not run')} |`)
  }
  const diff = report.regressions?.find(item => item.configDiff)?.configDiff
  if (diff) lines.push('', '## Configuration change preview', '', '```diff', diff, '```')

  if (report.policy.blockers.length) {
    lines.push('', '## Blocking reasons', '')
    for (const blocker of report.policy.blockers) lines.push(`- ${escapeMd(blocker.reason)}`)
  }
  lines.push('', `Generated by ${TOOL_NAME}. Static signatures require human review; absence of a finding is not proof of safety.`, '')
  return lines.join('\n')
}

export function badgeSvg(status) {
  const passed = status === 'pass'
  const label = passed ? 'compatible' : 'blocked'
  const color = passed ? '#2ea043' : '#d1242f'
  const width = passed ? 190 : 170
  return `<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="DSH plugin: ${label}" width="${width}" height="20"><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#fff" stop-opacity=".7"/><stop offset=".1" stop-color="#aaa" stop-opacity=".1"/><stop offset=".9" stop-color="#000" stop-opacity=".3"/><stop offset="1" stop-color="#000" stop-opacity=".5"/></linearGradient><clipPath id="r"><rect width="${width}" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="110" height="20" fill="#555"/><rect x="110" width="${width - 110}" height="20" fill="${color}"/><rect width="${width}" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11"><text x="55" y="15">DSH plugin</text><text x="${110 + (width - 110) / 2}" y="15">${label}</text></g></svg>\n`
}

export async function writeReports(report, directory) {
  const dir = resolve(directory)
  await mkdir(dir, { recursive: true })
  const stem = sanitizeFileName(report.plugin.name ?? 'plugin')
  const jsonPath = join(dir, `${stem}.doctor.json`)
  const markdownPath = join(dir, `${stem}.doctor.md`)
  const badgePath = join(dir, `${stem}.badge.svg`)
  report.artifacts = { jsonPath, markdownPath, badgePath }
  await writeJson(jsonPath, report)
  await writeFile(markdownPath, markdownReport(report))
  await writeFile(badgePath, badgeSvg(report.status))
  return report.artifacts
}

export function baseReport(source, plugin) {
  return {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    tool: { name: 'dsh-plugin-doctor', version: TOOL_VERSION },
    platform: { os: process.platform, arch: process.arch, node: process.version },
    source,
    plugin: { name: plugin.name, version: plugin.version },
  }
}
